src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MembreRepository::class)
 */
class Membre
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mot_de_passe;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $identifiant;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, inversedBy="membres")
     */
    private $roles;

    /**
     * @ORM\ManyToMany(targetEntity=Adoption::class, inversedBy="membres")
     */
    private $adoptions;

    public function __construct()
    {
        $this->roles = new ArrayCollection();
        $this->adoptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getMotDePasse(): ?string
    {
        return $this->mot_de_passe;
    }

    public function setMotDePasse(string $mot_de_passe): self
    {
        $this->mot_de_passe = $mot_de_passe;

        return $this;
    }

    public function getIdentifiant(): ?string
    {
        return $this->identifiant;
    }

    public function setIdentifiant(string $identifiant): self
    {
        $this->identifiant = $identifiant;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    /**
     * @return Collection<int, Role>
     */
    public function getRoles(): Collection
    {
        return $this->roles;
    }

    public function addRole(Role $role): self
    {
        if (!$this->roles->contains($role)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function removeRole(Role $role): self
    {
        $this->roles->removeElement($role);

        return $this;
    }

    /**
     * @return Collection<int, Adoption>
     */
    public function getAdoptions(): Collection
    {
        return $this->adoptions;
    }

    public function addAdoption(Adoption $adoption): self
    {
        if (!$this->adoptions->contains($adoption)) {
            $this->adoptions[] = $adoption;
        }

        return $this;
    }

    public function removeAdoption(Adoption $adoption): self
    {
        $this->adoptions->removeElement($adoption);

        return $this;
    }
}

src/Form/MembreType.php
<?php

namespace App\Form;

use App\Entity\Membre;
use App\Entity\Role;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MembreType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('mot_de_passe')
            ->add('identifiant')
            ->add('actif')
            ->add('roles'/* , EntityType::class, [
                'class'=>Role::class,
                'choice_label' => 'role',
                'multiple' => false,
                'expanded' => false,
            ] */)
            ->add('adoptions')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Membre::class,
        ]);
    }
}

src/Controller/MembreController.php
<?php

namespace App\Controller;

use App\Entity\Membre;
use App\Form\MembreType;
use App\Repository\MembreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/membre")
 */
class MembreController extends AbstractController
{
    /**
     * @Route("/", name="app_membre_index", methods={"GET"})
     */
    public function index(MembreRepository $membreRepository): Response
    {
        return $this->render('membre/index.html.twig', [
            'membres' => $membreRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_membre_new", methods={"GET", "POST"})
     */
    public function new(Request $request, MembreRepository $membreRepository): Response
    {
        $membre = new Membre();
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $membreRepository->add($membre);
            return $this->redirectToRoute('app_membre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('membre/new.html.twig', [
            'membre' => $membre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_membre_show", methods={"GET"})
     */
    public function show(Membre $membre): Response
    {
        return $this->render('membre/show.html.twig', [
            'membre' => $membre,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_membre_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Membre $membre, MembreRepository $membreRepository): Response
    {
        $form = $this->createForm(MembreType::class, $membre);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $membreRepository->add($membre);
            return $this->redirectToRoute('app_membre_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('membre/edit.html.twig', [
            'membre' => $membre,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_membre_delete", methods={"POST"})
     */
    public function delete(Request $request, Membre $membre, MembreRepository $membreRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$membre->getId(), $request->request->get('_token'))) {
            $membreRepository->remove($membre);
        }

        return $this->redirectToRoute('app_membre_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/membre/_delete_form.html.twig
<form method="post" action="{{ path('app_membre_delete', {'id': membre.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ membre.id) }}">
    <button class="btn">Delete</button>
</form>

templates/membre/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Membre{% endblock %}

{% block body %}
    <h1>Edit Membre</h1>

    {{ include('membre/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_membre_index') }}">back to list</a>

    {{ include('membre/_delete_form.html.twig') }}
{% endblock %}

templates/membre/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre index{% endblock %}

{% block body %}
    <h1>Membre index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Mot_de_passe</th>
                <th>Identifiant</th>
                <th>Actif</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for membre in membres %}
            <tr>
                <td>{{ membre.id }}</td>
                <td>{{ membre.nom }}</td>
                <td>{{ membre.prenom }}</td>
                <td>{{ membre.motDePasse }}</td>
                <td>{{ membre.identifiant }}</td>
                <td>{{ membre.actif ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_membre_show', {'id': membre.id}) }}">show</a>
                    <a href="{{ path('app_membre_edit', {'id': membre.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_membre_new') }}">Create new</a>
{% endblock %}

templates/membre/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Membre{% endblock %}

{% block body %}
    <h1>Create new Membre</h1>

    {{ include('membre/_form.html.twig') }}

    <a href="{{ path('app_membre_index') }}">back to list</a>
{% endblock %}

templates/membre/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Membre{% endblock %}

{% block body %}
    <h1>Membre</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ membre.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ membre.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ membre.prenom }}</td>
            </tr>
            <tr>
                <th>Mot_de_passe</th>
                <td>{{ membre.motDePasse }}</td>
            </tr>
            <tr>
                <th>Identifiant</th>
                <td>{{ membre.identifiant }}</td>
            </tr>
            <tr>
                <th>Actif</th>
                <td>{{ membre.actif ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_membre_index') }}">back to list</a>

    <a href="{{ path('app_membre_edit', {'id': membre.id}) }}">edit</a>

    {{ include('membre/_delete_form.html.twig') }}
{% endblock %}