src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnimalRepository::class)
 */
class Animal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tests;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $sexe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vaccins;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $commentaire;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $identification;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $sterilise;

    /**
     * @ORM\ManyToOne(targetEntity=FamilleAccueil::class, inversedBy="animaux")
     */
    private $familleAccueil;

    /**
     * @ORM\ManyToOne(targetEntity=Espece::class, inversedBy="animaux")
     */
    private $espece;

    /**
     * @ORM\ManyToMany(targetEntity=Adoption::class, inversedBy="animals")
     */
    private $adoption;

    public function __construct()
    {
        $this->adoption = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getTests(): ?string
    {
        return $this->tests;
    }

    public function setTests(?string $tests): self
    {
        $this->tests = $tests;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(?string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getVaccins(): ?string
    {
        return $this->vaccins;
    }

    public function setVaccins(?string $vaccins): self
    {
        $this->vaccins = $vaccins;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getIdentification(): ?string
    {
        return $this->identification;
    }

    public function setIdentification(?string $identification): self
    {
        $this->identification = $identification;

        return $this;
    }

    public function getSterilise(): ?bool
    {
        return $this->sterilise;
    }

    public function setSterilise(?bool $sterilise): self
    {
        $this->sterilise = $sterilise;

        return $this;
    }

    public function getFamilleAccueil(): ?FamilleAccueil
    {
        return $this->familleAccueil;
    }

    public function setFamilleAccueil(?FamilleAccueil $familleAccueil): self
    {
        $this->familleAccueil = $familleAccueil;

        return $this;
    }

    public function getEspece(): ?Espece
    {
        return $this->espece;
    }

    public function setEspece(?Espece $espece): self
    {
        $this->espece = $espece;

        return $this;
    }

    /**
     * @return Collection<int, Adoption>
     */
    public function getAdoption(): Collection
    {
        return $this->adoption;
    }

    public function addAdoption(Adoption $adoption): self
    {
        if (!$this->adoption->contains($adoption)) {
            $this->adoption[] = $adoption;
        }

        return $this;
    }

    public function removeAdoption(Adoption $adoption): self
    {
        $this->adoption->removeElement($adoption);

        return $this;
    }
}

src/Form/AnimalType.php
<?php

namespace App\Form;

use App\Entity\Adoption;
use App\Entity\Animal;
use App\Entity\Espece;
use App\Entity\FamilleAccueil;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnimalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'label' => 'Nom :',
                'attr' => ['placeholder' => 'Pepito'],
                ])
            ->add('date_naissance', DateType::class, [

                'label' => 'Date de naissance :',
                'widget' => 'single_text',
                ])
            ->add('statut', ChoiceType::class, [
                'label' => 'Statut :',
                'choices' => [
                    'Adoptable' => 'adoptable',
                    'Non adoptable' => 'non adoptable',
                ],
                'multiple' => false,
                'expanded' => false,

                'attr' => ['placeholder' => 'm/f ?'],
                ])
            ->add('tests', TextType::class, [
                'label' => 'Tests :',
                'attr' => ['placeholder' => ''],
                ])
            ->add('sexe', ChoiceType::class, [
                'label' => 'Sexe :',
                'choices' => [
                    'Masculin' => 'Masculin',
                    'Féminin' => 'Féminin',

                ],
                
                'multiple' => false,
                'expanded' => true,
                'mapped' => true,

                'attr' => ['placeholder' => 'm/f ?'],
                ])
            ->add('vaccins', TextType::class, [
                'label' => 'Vaccins :',
                'attr' => ['placeholder' => ''],
                ])
            ->add('photo', TextType::class, [
                'label' => 'Photo :',
                'attr' => ['placeholder' => 'Une photo s\'il vous plait !'],
                ])
            ->add('commentaire', TextareaType::class, [
                'label' => 'Commentaire :',
                'attr' => ['placeholder' => 'Woof? Woof? Bark! Bark!'],
                ])
            ->add('identification', TextType::class, [
                'label' => 'Identification :',
                'attr' => ['placeholder' => ''],
                ])
            ->add('sterilise', ChoiceType::class, [
                'label' => 'Stérilisé :',
                'choices' => [
                    'Oui' => 'Oui',
                    'Non' => 'Non',

                ],
                'multiple' => false,
                'expanded' => false,
                ])
            ->add('familleAccueil', EntityType::class, [
                // looks for choices from this entity
                'class' => FamilleAccueil::class,
                'choice_label' => 'nom',
                'label' => 'Accueilli par :',
                'required' => false,
                
                // used to render a select box, check boxes or radios
                'multiple' => false,
                'expanded' => false,
                'required' => false,
            ])
            ->add('espece', EntityType::class, [
                // looks for choices from this entity
                'class' => Espece::class,
                'choice_label' => 'type',
                'label' => 'Espèce :',
                // used to render a select box, check boxes or radios
                'multiple' => false,
                'expanded' => false,
            ]);
            /*->add('adoption', EntityType::class, [
                // looks for choices from this entity
                'class' => Adoption::class,
                'choice_label' => 'statut',
                'label' => "Statut d'adoption",
                // used to render a select box, check boxes or radios
                'multiple' => false,
                'expanded' => false,
            ]);*/
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Animal::class,
        ]);
    }
}

templates/animal/_form.html.twig
{% block body %}


    {{ form_start(form) }}

                {{ form_row(form.nom, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}
                {{ form_row(form.date_naissance, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.statut, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.tests, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.sexe, {'attr': {class:'form-control flex justify-around items-center mt-1 checked:bg-green-blue checked:border-green-blue focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-green-blue rounded-md  :'}}) }}
                {{ form_row(form.commentaire, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.identification, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.vaccins, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.photo, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.sterilise, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.familleAccueil, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}
                {{ form_row(form.espece, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md  :'}}) }}


                <div class="flex justify-between m-2">
                <button class="bg-white rounded-xl p-4  text-md font-normal leading-none text-black border-double border-2 border-black shadow-lg shadow-green-blue  hover:bg-green-blue  hover:-translate-y-1 hover:scale-110 hover:text-white font-bold">{{ button_label|default('Enregistrer') }}</button>
	            {# <a class="btn m-10" href="{{ path('app_animal_index') }}">Retour </a> #}
                <a href="{{ path('app_animal_index') }}" class="relative shadow-lg shadow-green-blue inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-black transition duration-300 ease-out border-2 border-black rounded-xl shadow-md group">
               <span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-green-blue group-hover:translate-x-0 ease">
                <svg class=" h-8 w-8 text-black-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                </svg>
             </span>
                <span class="absolute flex items-center justify-center w-full h-full text-black transition-all duration-300 transform group-hover:translate-x-full ease">Retour</span>
            <span class="relative invisible">Retour</span>
            </a>

              </div>

    {{ form_end(form) }}


{% endblock %}

templates/animal/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Animal
{% endblock %}

{% block body %}
	<main class="flex mx-auto ">

		<aside class="h-screen w-full xl:w-2/4 hidden lg:w-11/12 hidden xl:block lg:block lg:w-full h-screen md:hidden sm:hidden sm:w-full h-screen">
			<img class="max-w-full p-10 m-20 md:m-10 pt-20 mt-20" src=" {{ asset('build/images/dog-cat.png') }} " alt="dog-cat-home">
		</aside>

		<section class="flex mx-auto ">

			<div class="flex flex-col p-4 ">

				<div class=" p-4 text-center text-2xl rounded cursor-pointer">
					<p class="border-b-4 text-4xl mt-6 font-bold">
						Modifier l'animal
						<span class="material-icons">pets</span>
					</p>
				</div>

			
			<!-- ************************header formulaire*********************** -->


			{{ include('animal/_form.html.twig', {'button_label': 'Modifier'}) }}

			{#{ include('animal/_delete_form.html.twig') }#}
		</section>
	</main>
{% endblock %}

templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des animaux
{% endblock %}

{% block body %}
	<main class="flex w-full ">

		<section
			class="w-full p-4  ml-2">
			<!-- ************************header table*********************** -->

			<div class="px-4 md:px-10 py-4 md:py-7">
				<div class="flex items-center justify-center">
					<p tabindex="0" class="focus:outline-none text-2xl sm:text-2xl md:text-2xl lg:text-4xl font-bold leading-normal text-gray-800">Liste des animaux
						<span class="material-icons">pets</span>
					</p>
					{# <div class="py-3 px-4 flex items-center text-sm font-medium leading-none text-gray-600 bg-gray-200 hover:bg-gray-300 cursor-pointer rounded">
																				                    <p>Sort By:</p>
																				                    <select aria-label="select" class="focus:text-indigo-600 focus:outline-none bg-transparent ml-1">
																				                        <option class="text-sm text-indigo-800">Latest</option>
																				                        <option class="text-sm text-indigo-800">Oldest</option>
																				                        <option class="text-sm text-indigo-800">Latest</option>
																				                    </select>
																				                </div> #}
				</div>
			</div>
			<div class=" py-4 md:py-7 px-4 md:px-8 xl:px-10">
				<div class="sm:flex items-center justify-between mb-4 w-full">
					<p class="text-sm font-bold leading-none text-white ">
						<a class="text-sm font-bold leading-none " href="{{ path('app_animal_new') }}">
							<button class="bg-white rounded p-4 text-md font-normal leading-none text-black border-double border-2 border-black shadow-lg shadow-green-blue  hover:bg-green-blue  hover:-translate-y-1 hover:scale-110 hover:text-white font-bold">{{ button_label|default('Créer') }}</button>
						</a>
					</p>
				</div>
				<h1></h1>
				<!--************************************** table******************************* -->

				<table class="min-w-full border-collapse block md:table">
					<thead class="block md:table-header-group">
						<tr class="border border-grey-500 md:border-none block md:table-row absolute -top-full md:top-auto -left-full md:left-auto  md:relative ">
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Espèce</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Nom</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Date de naissance</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Statut</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Sexe</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Photo</th>

							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Actions</th>


						</tr>
					</thead>
					{# //**************** #}

					<tbody class="block md:table-row-group">
						{% for animal in animals %}

							<tr class="bg-gray-300 border border-grey-500 md:border-none block md:table-row">
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Espèce</span>
									{{ animal.espece.type }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Nom</span>
									{{ animal.nom }}</td>

								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/2 md:hidden font-bold uppercase">Date_naissance</span>
									{{ animal.dateNaissance  ? animal.dateNaissance|date('Y-m-d') : ''  }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Statut</span>
									{{ animal.statut }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase uppercase">Sexe</span>
									{{ animal.sexe }}</td>
								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold uppercase">Photo</span>
									 <img class="w-32" src="{{ animal.photo }}"></td>



								<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
									<span class="inline-block w-1/3 md:hidden font-bold">Actions</span>
									<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 border border-blue-500 rounded">
										<a href="{{ path('app_animal_show', {'id': animal.id}) }}">Détails</a>
									</button>
									{% if is_granted('ROLE_RESPONSABLE_POLE') %}
										<button class="bg-green-400 hover:bg-green-400 text-white font-bold py-1 px-2 border bord-bg-green-400 rounded">
											<a href="{{ path('app_animal_edit', {'id': animal.id}) }}">Modifier</a>
										</button>
									{% endif %}
									{# <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 border border-red-500 rounded">Archive</button> #}
								</td>
							</tr>
						
					
				
			{% else %}
				<tr>
					<td colspan="12">Aucune donnée</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</section></main>{% endblock body %}

templates/animal/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvel Animal{% endblock %}

{% block body %}
<main class="flex mx-auto ">

		<aside class="h-screen w-full xl:w-2/4 hidden lg:w-11/12 hidden xl:block lg:block lg:w-full h-screen md:hidden sm:hidden sm:w-full h-screen">
			<img class="max-w-full p-10 m-20 md:m-10 pt-20 mt-20" src=" {{ asset('build/images/dog-cat.png') }} " alt="dog-cat-home">
		</aside>

		<section class="flex mx-auto">

			<div class="flex flex-col p-4 ">

				<div class=" p-4 text-center text-2xl rounded cursor-pointer">
					<p class="border-b-4 text-4xl mt-6 font-bold">
						Nouvel animal <span class="material-icons">pets</span>
					</p>
				</div>
       <!-- ************************header table*********************** -->


    {{ include('animal/_form.html.twig') }}

</section >
</main >
{% endblock %}

templates/animal/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal{% endblock %}

{% block body %}
	<main class="flex ">

		<section class="mx-auto">

				<div class=" p-4 text-center text-2xl rounded cursor-pointer">
					<p class="border-b-4 text-4xl mt-6 font-bold">
						Détails sur {{ animal.nom }}
						<span class="material-icons">pets</span>
					</p>
				</div>
                {# Name of the animal #}
           <div class="flex flex-col p-4 sm:flex-row">
                    <figure class="flex flex-col max-w-xl p-4">
                             <div class="rounded-md border-8 border-green-blue max-w-xl ">
                                <img class="w-full" src=" {{ animal.photo }} " alt="{{ animal.nom }}">
                            </div>
                            <figcaption class="text-center text-xl m-4">
                                <h2 class="text-center font-bold text-xl">Commentaire :</h2>
                                <p>{{ animal.commentaire }}</p>
                            </figcaption>
                    </figure>

                 {#image of the animal #}
                <div class="flex flex-col p-4  items-center justify-center">
                {#details and the button of the animal #}
                    <div class="flex items-center justify-around">
                        <table class="table-auto flex justify-around">
                        <tbody  class="table-auto text-center text-xl">
                            <tr >
                                <th class="text-left">Espèce :</th>
                                <td >{{ animal.espece.type}}</td>
                            </tr>
                            <tr >
                                <th class="pt-2 m-1 text-left">Date de naissance :</th>
                                <td class="">{{ animal.dateNaissance ? animal.dateNaissance|date('Y-m-d') : '' }}</td>
                            </tr>
                            <tr>
                                <th class="pt-2 m-1 text-left">Statut d'adoption :</th>
                                <td>{{ animal.statut }}</td>
                            </tr>

                            <tr>
                                <th class="pt-2 m-1 text-left">Tests :</th>
                                <td>{{ animal.tests }}</td>
                            </tr>
                            <tr>
                                <th class="pt-2 m-1 text-left">Sexe :</th>
                                <td>{{ animal.sexe }}</td>
                            </tr>
                            <tr>
                                <th class="pt-2 m-1 text-left">Vaccins :</th>
                                <td>{{ animal.vaccins }}</td>
                            </tr>
                            <tr>
                                <th class="pt-2 m-1 text-left">Identification :</th>
                                <td>{{ animal.identification }}</td>
                            </tr>
                            <tr>
                                <th class="pt-2 m-1 text-left">Sterilise :</th>
                                <td>{{ animal.sterilise ? 'Yes' : 'No' }}</td>
                            </tr>
                            <tr>
                                <th class="pt-2 m-1 text-left">Famille d'accueil :</th>
                                <td>{{ animal.FamilleAccueil.prenom ?? "Personne"}} {{ animal.FamilleAccueil.nom ?? ""}} à {{ animal.FamilleAccueil.ville ?? ""}}</td>
                            </tr>
                            
                        </tbody>
                        </table>
                    </div>
             {#details of the animal #}
                    <div class="flex flex-row p-4">
                        <div class="flex flex-col p-4">
                            <a class="text-sm font-bold leading-none text-white " href="{{ path('app_animal_edit', {'id': animal.id}) }}">
                            <button class="bg-white rounded-xl p-5 text-md font-normal leading-none text-black border-double border-2 border-black shadow-lg shadow-green-blue  hover:bg-green-blue  hover:-translate-y-1 hover:scale-110 hover:text-white font-bold">Modifier</button>
                            </a>
                        </div>
                        <div class="flex flex-col p-4">
                            <a href="{{ path('app_animal_index') }}" class="relative  shadow-lg shadow-green-blue inline-flex items-center justify-center p-4 overflow-hidden font-medium text-black transition duration-300 ease-out border-2 border-black rounded-xl shadow-md group">
                                <span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-green-blue group-hover:translate-x-0 ease">
                                    <svg class=" h-8 w-8 text-black-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                                    </svg>
                                </span>
                                <span class="absolute flex items-center justify-center w-full h-full text-black transition-all duration-300 transform group-hover:translate-x-full ease">Retour</span>
                                <span class="relative invisible">Retour</span>
                            </a>
                        </div>
                    </div>
              {#buttons #}
             </div>
         
           </div> 


    {# {{ include('animal/_delete_form.html.twig') }} #}
   
</section >
</main >
{% endblock %}