src/Entity/Adoptant.php
<?php

namespace App\Entity;

use App\Repository\AdoptantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdoptantRepository::class)
 */
class Adoptant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $code_postal;

    /**
     * @ORM\OneToMany(targetEntity=Adoption::class, mappedBy="adoptant")
     */
    private $adoptions;

    /**
     * @ORM\OneToMany(targetEntity=Calendar::class, mappedBy="adoptant")
     */
    private $calendars;

    public function __construct()
    {
        $this->adoptions = new ArrayCollection();
        $this->calendars = new ArrayCollection();
    }

    public function __toString()
    {
        $result = $this->telephone;
        return (string) $result;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(?string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    /**
     * @return Collection<int, Adoption>
     */
    public function getAdoptions(): Collection
    {
        return $this->adoptions;
    }

    public function addAdoption(Adoption $adoption): self
    {
        if (!$this->adoptions->contains($adoption)) {
            $this->adoptions[] = $adoption;
            $adoption->setAdoptant($this);
        }

        return $this;
    }

    public function removeAdoption(Adoption $adoption): self
    {
        if ($this->adoptions->removeElement($adoption)) {
            // set the owning side to null (unless already changed)
            if ($adoption->getAdoptant() === $this) {
                $adoption->setAdoptant(null);
            }
        }

        return $this;
    }

    public function getFullname()
    {
        return $this->prenom . ' ' . $this->nom;
    }

    /**
     * @return Collection<int, Calendar>
     */
    public function getCalendars(): Collection
    {
        return $this->calendars;
    }

    public function addCalendar(Calendar $calendar): self
    {
        if (!$this->calendars->contains($calendar)) {
            $this->calendars[] = $calendar;
            $calendar->setAdoptant($this);
        }

        return $this;
    }

    public function removeCalendar(Calendar $calendar): self
    {
        if ($this->calendars->removeElement($calendar)) {
            // set the owning side to null (unless already changed)
            if ($calendar->getAdoptant() === $this) {
                $calendar->setAdoptant(null);
            }
        }

        return $this;
    }
}

src/Entity/Adoption.php
<?php

namespace App\Entity;

use App\Repository\AdoptionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AdoptionRepository::class)
 */
class Adoption
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_appel;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $compte_rendu;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $retour_animaux_proposes;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_rencontre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $retour_rencontre_adoptant;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $retour_rencontre_fa;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_visite;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $retour_visite;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_adoption;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_depart;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $remarque;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity=Adoptant::class, inversedBy="adoptions")
     */
    private $adoptant;

    /**
     * @ORM\ManyToMany(targetEntity=Membre::class, mappedBy="adoptions")
     */
    private $membres;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $animaux_proposes;

    /**
     * @ORM\ManyToMany(targetEntity=Animal::class, mappedBy="adoption")
     */
    private $animals;

    public function __construct()
    {
        $this->membres = new ArrayCollection();
        $this->animals = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateAppel(): ?\DateTimeInterface
    {
        return $this->date_appel;
    }

    public function setDateAppel(?\DateTimeInterface $date_appel): self
    {
        $this->date_appel = $date_appel;

        return $this;
    }

    public function getCompteRendu(): ?string
    {
        return $this->compte_rendu;
    }

    public function setCompteRendu(?string $compte_rendu): self
    {
        $this->compte_rendu = $compte_rendu;

        return $this;
    }

    public function getRetourAnimauxProposes(): ?string
    {
        return $this->retour_animaux_proposes;
    }

    public function setRetourAnimauxProposes(?string $retour_animaux_proposes): self
    {
        $this->retour_animaux_proposes = $retour_animaux_proposes;

        return $this;
    }

    public function getDateRencontre(): ?\DateTimeInterface
    {
        return $this->date_rencontre;
    }

    public function setDateRencontre(?\DateTimeInterface $date_rencontre): self
    {
        $this->date_rencontre = $date_rencontre;

        return $this;
    }

    public function getRetourRencontreAdoptant(): ?string
    {
        return $this->retour_rencontre_adoptant;
    }

    public function setRetourRencontreAdoptant(?string $retour_rencontre_adoptant): self
    {
        $this->retour_rencontre_adoptant = $retour_rencontre_adoptant;

        return $this;
    }

    public function getRetourRencontreFa(): ?string
    {
        return $this->retour_rencontre_fa;
    }

    public function setRetourRencontreFa(?string $retour_rencontre_fa): self
    {
        $this->retour_rencontre_fa = $retour_rencontre_fa;

        return $this;
    }

    public function getDateVisite(): ?\DateTimeInterface
    {
        return $this->date_visite;
    }

    public function setDateVisite(?\DateTimeInterface $date_visite): self
    {
        $this->date_visite = $date_visite;

        return $this;
    }

    public function getRetourVisite(): ?string
    {
        return $this->retour_visite;
    }

    public function setRetourVisite(?string $retour_visite): self
    {
        $this->retour_visite = $retour_visite;

        return $this;
    }

    public function getDateAdoption(): ?\DateTimeInterface
    {
        return $this->date_adoption;
    }

    public function setDateAdoption(?\DateTimeInterface $date_adoption): self
    {
        $this->date_adoption = $date_adoption;

        return $this;
    }

    public function getDateDepart(): ?\DateTimeInterface
    {
        return $this->date_depart;
    }

    public function setDateDepart(?\DateTimeInterface $date_depart): self
    {
        $this->date_depart = $date_depart;

        return $this;
    }

    public function getRemarque(): ?string
    {
        return $this->remarque;
    }

    public function setRemarque(?string $remarque): self
    {
        $this->remarque = $remarque;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getAdoptant(): ?Adoptant
    {
        return $this->adoptant;
    }

    public function setAdoptant(?Adoptant $adoptant): self
    {
        $this->adoptant = $adoptant;

        return $this;
    }

    /**
     * @return Collection<int, Membre>
     */
    public function getMembres(): Collection
    {
        return $this->membres;
    }

    public function addMembre(Membre $membre): self
    {
        if (!$this->membres->contains($membre)) {
            $this->membres[] = $membre;
            $membre->addAdoption($this);
        }

        return $this;
    }

    public function removeMembre(Membre $membre): self
    {
        if ($this->membres->removeElement($membre)) {
            $membre->removeAdoption($this);
        }

        return $this;
    }

    public function getAnimauxProposes(): ?string
    {
        return $this->animaux_proposes;
    }

    public function setAnimauxProposes(?string $animaux_proposes): self
    {
        $this->animaux_proposes = $animaux_proposes;

        return $this;
    }

    /**
     * @return Collection<int, Animal>
     */
    public function getAnimals(): Collection
    {
        return $this->animals;
    }

    public function addAnimal(Animal $animal): self
    {
        if (!$this->animals->contains($animal)) {
            $this->animals[] = $animal;
            $animal->addAdoption($this);
        }

        return $this;
    }

    public function removeAnimal(Animal $animal): self
    {
        if ($this->animals->removeElement($animal)) {
            $animal->removeAdoption($this);
        }

        return $this;
    }
}

src/Form/AdoptantType.php
<?php

namespace App\Form;

use App\Entity\Adoptant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class AdoptantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
            'label' => 'Nom :',
             'required' => false,
             'attr' => ['placeholder' => 'Poti'],
             ])
            ->add('prenom', TextType::class, [
                'label' => 'Prénom :',
                'required' => false,
                'attr' => ['placeholder' => 'Poutchi'],
                ])
            ->add('adresse', TextType::class,[
                'label' => 'Adresse :',
                'required' => false,
                'attr' => ['placeholder' => '00 avenue des petites patates'],
                ])
            ->add('telephone', TextType::class, [
                'label' => 'Téléphone :',
                'attr' => ['placeholder' => '1234567890'],
            ])
            ->add('email', EmailType::class, [
                'label' => 'E-mail :',
                'required' => false,
                'attr' => ['placeholder' => 'mail@example.com'],
                ])
            ->add('ville', TextType::class, [
                'label' => 'Ville :',
                'attr' => ['placeholder' => 'Paris'],
                'required' => false,
            ])
            ->add('code_postal', IntegerType::class, [
                'label' => 'Code Postal : ',
                'attr' => ['placeholder' => '98745'],
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Adoptant::class,
        ]);
    }
}

src/Controller/AdoptantController.php
<?php

namespace App\Controller;

use App\Entity\Adoptant;
use App\Entity\Adoption;
use App\Form\AdoptantType;
use App\Repository\AdoptantRepository;
use App\Repository\AdoptionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * @Route("/adoptant")
 */
class AdoptantController extends AbstractController
{
    /**
     * @Route("/", name="app_adoptant_index", methods={"GET"})
     */
    public function index(AdoptantRepository $adoptantRepository): Response
    {
        return $this->render('adoptant/index.html.twig', [
            'adoptants' => $adoptantRepository->findAll(),
        ]);
    }

    /**
     * @IsGranted("ROLE_RESPONSABLE_POLE")
     * @Route("/ajout", name="app_adoptant_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AdoptantRepository $adoptantRepository): Response
    {
        $adoptant = new Adoptant();
        $form = $this->createForm(AdoptantType::class, $adoptant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $adoptantRepository->add($adoptant);
            return $this->redirectToRoute('app_adoptant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('adoptant/new.html.twig', [
            'adoptant' => $adoptant,
            'form' => $form,
        ]);
    }

    /**
     * @IsGranted("ROLE_RESPONSABLE_POLE")
     * @Route("/{id}", name="app_adoptant_show", methods={"GET"})
     */
    public function show(Adoptant $adoptant , AdoptionRepository $adoptionRepository): Response
    {
        return $this->render('adoptant/show.html.twig', [
            'adoptant' => $adoptant,
            'adoptions' => $adoptionRepository->findByAdoptant($adoptant),
        ]);
    }

    /**
     * @Route("/{id}/modification/{idAdoption}", name="app_adoptant_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Adoptant $adoptant, AdoptantRepository $adoptantRepository,EntityManagerInterface $entityManager, int $idAdoption ): Response
    {
        $form = $this->createForm(AdoptantType::class, $adoptant);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            
            $adoptantRepository->add($adoptant);
            

            $entityManager->flush();
            
            return $this->redirectToRoute('app_adoption_edit', [
                'id'=> $idAdoption
                
            ]);
        }

        return $this->renderForm('adoptant/edit.html.twig', [
            'adoptant' => $adoptant,
            'form' => $form,
        ]);
    }

    // TODO Gérer l'archivage
    /**
     * @Route("/{id}", name="app_adoptant_delete", methods={"POST"})
     */
    /* public function delete(Request $request, Adoptant $adoptant, AdoptantRepository $adoptantRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$adoptant->getId(), $request->request->get('_token'))) {
            $adoptantRepository->remove($adoptant);
        }

        return $this->redirectToRoute('app_adoptant_index', [], Response::HTTP_SEE_OTHER);
    } */

}

templates/adoptant/_form.html.twig
{% block body %}

{{ form_start(form) }}


{{ form_row(form.nom, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}
{{ form_row(form.prenom, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}
{{ form_row(form.adresse, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}
{{ form_row(form.telephone, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}
{{ form_row(form.email, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}
{{ form_row(form.ville, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}
{{ form_row(form.code_postal, {'attr': {class:'form-control mt-1 focus:ring-green-blue focus:border-green-blue block w-full shadow-sm sm:text-sm border-gray-300 rounded-md :'}}) }}

    {{ form_widget(form) }}

	{# <div>
    <button class="btn m-20 ml-5 mr-5">{{ button_label|default('Sauvegarde') }}</button> #}

    
    {# <a href="{{ path('app_adoptant_index') }}"><button class="btn m-20 ml-5 mr-5">Ajouter une adoption</button></a> #}
      <div class="flex justify-between m-4">
                <button class="bg-white rounded-xl p-4  text-md font-normal leading-none text-black border-double border-2 border-black shadow-lg shadow-green-blue  hover:bg-green-blue  hover:-translate-y-1 hover:scale-110 hover:text-white font-bold">{{ button_label|default('Enregistrer') }}</button>
	            
                <a href="{{ path('app_adoptant_index') }}" class="relative shadow-lg shadow-green-blue inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-black transition duration-300 ease-out border-2 border-black rounded-xl shadow-md group">
               <span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-green-blue group-hover:translate-x-0 ease">
                <svg class=" h-8 w-8 text-black-500"  fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
                </svg>
             </span>
                <span class="absolute flex items-center justify-center w-full h-full text-black transition-all duration-300 transform group-hover:translate-x-full ease">Retour</span>
            <span class="relative invisible">Retour</span>
            </a>

              </div>

{{ form_end(form) }}

{% endblock %}

templates/adoptant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification Adoptant{% endblock %}

{% block body %}

<main class="flex justify-center items-center  ">

    <section class=" border-2 p-10  ml-2">
        {# <div class="px-10 md:px-12 py-10 md:py-7">
            <div class="flex items-center justify-between">
                <p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800">Edit Adoptant </p>
            </div>
        </div> #}
    
	{# <a  href="{{ path('app_adoptant_index') }}"><button class="btn m-20 ml-5 mr-5">Retour</button></a>
    </div> #}
    {# <a  href="{{ path('app_adoptant_index') }}">Retour</a> #}

    {# {{ include('adoptant/_delete_form.html.twig') }} #}

<main class="flex mx-auto ">

		<aside class="h-screen w-full xl:w-2/4 hidden lg:w-11/12 hidden xl:block lg:block lg:w-full h-screen md:hidden sm:hidden sm:w-full h-screen">
			<img class="max-w-full p-10 m-20 md:m-10 pt-20 mt-20" src=" {{ asset('build/images/dog-cat.png') }} " alt="dog-cat-home">
		</aside>

		<section class="flex mx-auto ">

			<div class="flex flex-col p-4 ">

				<div class=" p-4 text-center text-2xl rounded cursor-pointer">
					<p class="border-b-4 text-4xl mt-6 font-bold">
						Modifier un adoptant <span class="material-icons">pets</span>
					</p>
				</div>

    {{ include('adoptant/_form.html.twig', {'button_label': 'Modifier'}) }}



			</div >
		</section >
</main >
{% endblock %}

templates/adoptant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Adoptant{% endblock %}

{% block body %}
<main class="flex justify-center items-center  ">

      <section class=" border-2 p-10  ml-2">
      <div class="px-10 md:px-12 py-10 md:py-7">
      <div class="flex items-center justify-between">
                <p tabindex="0" class="focus:outline-none text-base sm:text-lg md:text-xl lg:text-2xl font-bold leading-normal text-gray-800"></p>
                </div>
       </div>
       <!-- ************************header table*********************** -->



    {{ include('adoptant/_form.html.twig') }}

    </div >
</section >
</main >
{% endblock %}

templates/adoptant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adoptant
{% endblock %}

{% block body %}
	<main class="flex ">
		<aside class="h-screen w-full xl:w-2/4 hidden lg:w-11/12 hidden xl:block lg:block lg:w-full h-screen md:hidden sm:hidden sm:w-full h-screen">
			<img class="max-w-full p-10 m-20 md:m-10 pt-20 mt-20" src="https://images.pexels.com/photos/6864965/pexels-photo-6864965.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="dog-cat-home">
		</aside>

		<section class="mx-auto">

			<div class=" p-4 text-center text-2xl rounded cursor-pointer">
				<p class="border-b-4 text-4xl mt-6 font-bold">
					Détails sur
					{{ adoptant.prenom ?? ""}}
					{{ adoptant.nom ?? ""}}
					<span class="material-icons">pets</span>
				</p>
			</div>
			<!-- ************************header table*********************** -->

			<div class="flex items-center justify-around">

				<table class="table-auto flex justify-around">
					<tbody class="table-auto text-center text-xl">

						<tr>
							<th class="text-left">Adresse :</th>
							<td>{{ adoptant.adresse }}</td>
						</tr>
						<tr>
							<th></th>
							<td>{{ adoptant.codePostal }}
								{{ adoptant.ville }}</td>
						</tr>

						<tr>
							<th class="pt-2 m-1 text-left">Téléphone :</th>
							<td>{{ adoptant.telephone }}</td>
						</tr>
						<tr>
							<th class="pt-2 m-1 text-left">Email :</th>
							<td>{{ adoptant.email }}</td>
						</tr>

					</tbody>
				</table>

			</div>
			<div class="flex p-4">
				<table class="min-w-full border-collapse block md:table ">
					<thead class="block md:table-header-group">
						<tr class="border border-grey-500  md:border-none block md:table-row absolute -top-full md:top-auto -left-full md:left-auto  md:relative ">
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Statut</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Date</th>
							<th class="bg-gray-600 p-2 text-white text-center font-bold md:border md:border-grey-500 text-left block md:table-cell">Action</th>
						</tr>
					</thead>
					<tbody class="block  md:table-row-group ">
						{% for adoption in adoptions %}
							<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
								<span class="inline-block w-1/3 md:hidden font-bold uppercase">Statut</span>
								{{ adoption.statut }}</td>
							<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
								<span class="inline-block w-1/3 md:hidden font-bold uppercase">Date d'appel</span>
								{{ adoption.dateAppel ? adoption.dateAppel|date('Y-m-d') : '' }}</td>
							<td class="p-2 md:border md:border-grey-500 text-left block md:table-cell">
								<span class="inline-block w-1/3 md:hidden font-bold uppercase">Détails</span>
								<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-1 px-2 border border-blue-500 rounded">
									<a href="{{ path('app_adoption_show', {'id': adoption.id}) }}">Détails</a>
								</button>
							</td>
						</tr>
					</tbody>
				</td>
			{% endfor %}
		</tbody>
	</table>

</div>

<div
	class="flex justify-between m-2">
	{# <a class="text-sm font-bold leading-none text-white " href="{{ path('app_adoptant_edit', {'id': adoptant.id}) }}">
			                <button class="bg-white rounded p-4 text-md font-normal leading-none text-black border-double border-2 border-black shadow-lg shadow-green-blue  hover:bg-green-blue  hover:-translate-y-1 hover:scale-110 hover:text-white font-bold">Modifier</button>
			                </a> #}

	<a href="{{ path('app_adoptant_index') }}" class="relative shadow-lg shadow-green-blue inline-flex items-center justify-center p-4 px-6 py-3 overflow-hidden font-medium text-black transition duration-300 ease-out border-2 border-black rounded-xl shadow-md group">
		<span class="absolute inset-0 flex items-center justify-center w-full h-full text-white duration-300 -translate-x-full bg-green-blue group-hover:translate-x-0 ease">
			<svg class=" h-8 w-8 text-black-500" fill="none" viewbox="0 0 24 24" stroke="currentColor">
				<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"/>
			</svg>
		</span>
		<span class="absolute flex items-center justify-center w-full h-full text-black transition-all duration-300 transform group-hover:translate-x-full ease">Retour</span>
		<span class="relative invisible">Retour</span>
	</a>
</div></section></main>{# {{ include('adoptant/_delete_form.html.twig') }} #}{% endblock %}